title: Yichong Dong | Academic Homepage
page-top-title: Yichong Dong
top-section-bg-text: Marine Sustainability, Fisheries Economics, and Policy
home-subtitle: ABOUT
copyright-text: '&copy; Yichong Dong 2026. All Rights Reserved.'
